/**
 * Snapshot mockdata/*.ts into src/db/fixtures.json.
 *
 * The seeder needs to run inside the compiled server (so it can be triggered
 * from the admin UI), but the fixtures are TypeScript modules outside this
 * package that `tsc` will not emit. A JSON snapshot is importable from
 * compiled code and gets copied into dist by `resolveJsonModule`.
 *
 * Regenerated by `npm run build` and `npm run dev`, so editing mockdata/ is
 * still the way to change the demo data.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import * as data from "../../mockdata/index.js";
import { aiContentBySlug } from "../../mockdata/ai.js";

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/db/fixtures.json");

const fixtures = {
  categories: data.categories,
  products: data.products,
  orders: data.orders,
  customers: data.customers,
  feedback: data.feedback,
  promotions: data.promotions,
  heroSlides: data.heroSlides,
  productExtras: data.productExtras,
  aiContent: aiContentBySlug,
};

writeFileSync(out, JSON.stringify(fixtures, null, 2) + "\n");
const counts = Object.entries(fixtures)
  .map(([k, v]) => `${k}=${Array.isArray(v) ? v.length : Object.keys(v).length}`)
  .join(" ");
console.log(`wrote ${out}\n  ${counts}`);
